sequence:
  - service: switch.turn_on
    data:
      entity_id: switch.zmietek
  - wait_for_trigger:
    - platform: state
      entity_id: sensor.vacuum_battery
      to: '90'
    timeout: 600
    continue_on_timeout: true
  - service: vacuum.start
    data:
      entity_id: vacuum.zmietekv2
  - service: notify.mypushbullet
    data_template:
      title: 'Zmietek start'
      message: |
        {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
        Zmietek start z poziomem baterii {{ state_attr('vacuum.zmietekv2', 'battery_level') }} %.
