- platform: template
  switches:
    xbox_power_switch:
      friendly_name: Xbox power switch
      entity_id:
        - binary_sensor.xsx_online
        - switch.listwa_salon_slot_2
      value_template: "{{ is_state('switch.listwa_salon_slot_2', 'on') }}"
      availability_template: "{{is_state('binary_sensor.xsx_online', 'off') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.listwa_salon_slot_2
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.listwa_salon_slot_2
#    ps4_power_switch:
#      friendly_name: PS4 power switch
#      entity_id:
#        - binary_sensor.playstation_4_online
#        - switch.listwa_salon_slot_3
#      value_template: "{{ is_state('switch.listwa_salon_slot_3', 'on') }}"
#      availability_template: "{{ is_state('binary_sensor.playstation_4_online', 'off') }}"
#      turn_on:
#        service: switch.turn_on
#        data:
#          entity_id: switch.listwa_salon_slot_3
#      turn_off:
#        service: switch.turn_off
#        data:
#          entity_id: switch.listwa_salon_slot_3
    listwa_sypialnia_switch:
      friendly_name: Listwa sypialnia switch
      entity_id:
        - media_player.sypialnia_chromecast
        - switch.listwa_sypialnia
      value_template: "{{ is_state('switch.listwa_sypialnia', 'on') }}"
      availability_template: "{{-
        is_state('media_player.sypialnia_chromecast','on')
          or
        is_state('media_player.sypialnia_chromecast','off')
          or
        is_state('media_player.sypialnia_chromecast','unavailable')
        -}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.listwa_sypialnia
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.listwa_sypialnia
    listwa_jan_switch:
      friendly_name: Listwa jan switch
      entity_id:
        - binary_sensor.xbox_online
        - binary_sensor.sharp_online
        - media_player.pokoj_janka
        - switch.rtv_jan
      value_template: "{{ is_state('switch.rtv_jan', 'on') }}"
      availability_template: "{{-
          is_state('binary_sensor.xbox_online', 'off')
        and
          is_state('binary_sensor.sharp_online', 'off')
        and
        (
          is_state('media_player.pokoj_janka','unavailable')
        or
          is_state('media_player.pokoj_janka','off')
        or
          is_state('media_player.pokoj_janka','on')
          )
        -}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.rtv_jan
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.rtv_jan
