- alias: 'Pozar w kuchni'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kuchnia_smoke_detector
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_salon_slot_4
    - service: notify.mypushbullet
      data_template:
        title: "!! Pożar w kuchni !!"
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Pożar kuchni!!! Podgląd z kamery.