- alias: 'Zalanie kuchni'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kuchnia_leak_water_leak
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_salon_slot_4
    - service: notify.mypushbullet
      data_template:
        title: "!! Zalanie kuchni !!"
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Zalanie kuchni!!! Podgląd z kamery.
