zamioculcas_zamiifolia:
  sensors:
#    moisture: sensor.mi_m_c47c8d6a0192
    moisture: sensor.zamioculcas_zamiifolia_moisture
    battery: sensor.zamioculcas_zamiifolia_battery
#    temperature: sensor.mi_t_c47c8d6a0192
    temperature: sensor.zamioculcas_zamiifolia_temperature
#    conductivity: sensor.mi_c_c47c8d6a0192
    conductivity: sensor.zamioculcas_zamiifolia_conductivity
    brightness: sensor.mi_l_c47c8d6a0192
  min_moisture: 15
  max_moisture: 60
  min_battery: 20
  min_conductivity: 350
  max_conductivity: 2000
  min_temperature: 10
  max_temperature: 32

#sansevieria_trifasciata:
#  sensors:
#    moisture: sensor.sansevieria_trifasciata_moisture
#    battery: sensor.sansevieria_trifasciata_battery
#    temperature: sensor.sansevieria_trifasciata_temperature
#    conductivity: sensor.sansevieria_trifasciata_conductivity
#    brightness: sensor.sansevieria_trifasciata_light_intensity
#  min_moisture: 7
#  max_moisture: 50
#  min_battery: 20
#  min_conductivity: 300
#  max_conductivity: 1000
#  min_temperature: 10
#  max_temperature: 32

#crassula_ovata:
#  sensors:
#    moisture: sensor.spathiphyllum_moisture
#    battery: sensor.spathiphyllum_battery
#    temperature: sensor.spathiphyllum_temperature
#    conductivity: sensor.spathiphyllum_conductivity
#    brightness: sensor.spathiphyllum_light_intensity
#  min_moisture: 7
#  max_moisture: 50
#  min_battery: 20
#  min_conductivity: 50
#  max_conductivity: 1000
#  min_temperature: 8
#  max_temperature: 35

#ficus_benjamina:
#  sensors:
#    moisture: sensor.ficus_moisture
#    battery: sensor.ficus_battery
#    temperature: sensor.ficus_temperature
#    conductivity: sensor.ficus_conductivity
#    brightness: sensor.ficus_light_intensity
#  min_moisture: 20
#  max_moisture: 60
#  min_battery: 20
#  min_conductivity: 350
#  max_conductivity: 2000
#  min_temperature: 8
#  max_temperature: 32
#
#dracaena_marginata:
#  sensors:
#    moisture: sensor.mi_m_c47c8d69fef0
#    battery: sensor.dracaena_marginata_battery
#    temperature: sensor.mi_t_c47c8d69fef0
#    conductivity: sensor.mi_c_c47c8d69fef0
#    brightness: sensor.mi_l_c47c8d69fef0
#  min_moisture: 15
#  max_moisture: 60
#  min_battery: 20
#  min_conductivity: 350
#  max_conductivity: 2000
#  min_temperature: 10
#  max_temperature: 32

#agave_univittata:
#  sensors:
#    moisture: sensor.agave_moisture
#    battery: sensor.agave_battery
#    temperature: sensor.agave_temperature
#    conductivity: sensor.agave_conductivity
#    brightness: sensor.agave_light_intensity
#  min_moisture: 7
#  max_moisture: 50
#  min_battery: 20
#  min_conductivity: 300
#  max_conductivity: 1000
#  min_temperature: 7
#  max_temperature: 35

spathiphyllum:
  sensors:
#    moisture: sensor.mi_m_c47c8d6b24c7
    moisture: sensor.spathiphyllum_moisture
    battery: sensor.spathiphyllum_battery
#    temperature: sensor.mi_t_c47c8d6b24c7
    temperature: sensor.spathiphyllum_temperature
#    conductivity: sensor.mi_c_c47c8d6b24c7
    conductivity: sensor.spathiphyllum_conductivity
    brightness: sensor.mi_l_c47c8d6b24c7
  min_moisture: 15
  max_moisture: 65
  min_battery: 20
  min_conductivity: 350
  max_conductivity: 2000
  min_temperature: 15
  max_temperature: 32

pachira:
  sensors:
#    moisture: sensor.mi_m_c47c8d6b5ab1
    moisture: sensor.pachira_moisture
    battery: sensor.pachira_battery
#    temperature: sensor.mi_t_cc47c8d6b5ab1
    temperature: sensor.pachira_temperature
#    conductivity: sensor.mi_c_cc47c8d6b5ab1
    conductivity: sensor.pachira_conductivity
    brightness: sensor.mi_l_cc47c8d6b5ab1
  min_moisture: 15
  max_moisture: 60
  min_battery: 20
  min_conductivity: 350
  max_conductivity: 2000
  min_temperature: 10
  max_temperature: 32

#yucca_elephantipes:
#  sensors:
#    moisture: sensor.mi_m_c47c8d6b1ab3
#    battery: sensor.yucca_elephantipes_battery
#    temperature: sensor.mi_t_c47c8d6b1ab3
#    conductivity: sensor.mi_c_c47c8d6b1ab3
#    brightness: sensor.mi_l_c47c8d6b1ab3
#  min_moisture: 15
#  max_moisture: 60
#  min_battery: 20
#  min_conductivity: 350
#  max_conductivity: 2000
#  min_temperature: 8
#  max_temperature: 32
