- platform: template
  sensors:
    purifier_mode:
      value_template: "{{ states.fan.purifier.attributes.mode }}"
      friendly_name: "Mode"
      icon_template: mdi:fan
    motor_speed:
      value_template: "{{ states.fan.purifier.attributes.motor_speed }}"
      friendly_name: "Motor speed"
      icon_template: mdi:fan
    purifier_temperature:
      value_template: "{{ states.fan.purifier.attributes.temperature }}"
      friendly_name: "Purifier"
      unit_of_measurement: "°C"
    purifier_humidity:
      value_template: "{{ states.fan.purifier.attributes.humidity }}"
      friendly_name: "Purifier"
      unit_of_measurement: "%"
    purifier_aqi:
      value_template: "{{ states.fan.purifier.attributes.aqi }}"
      friendly_name: "aqi"
    purifier_filter_type:
      value_template: "{{ states.fan.purifier.attributes.filter_type }}"
      friendly_name: "Filter type"
    purifier_filter_life_remaining:
      friendly_name: "Filter life remaining"
      unit_of_measurement: "%"
      value_template: "{{ states.fan.purifier.attributes.filter_life_remaining }}"
