#- platform: mitemp_bt
#  rounding: True
#  decimals: 2
#  period: 60
#  log_spikes: False
#  use_median: False
#  active_scan: True
#  hci_interface: 0
##  encryptors:
##    'A4:C1:38:A3:70:35': '217C568CF5D22808DA20181502D84C1B'
#  report_unknown: False
