- platform: mitemp_bt
  rounding: True
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  active_scan: False
  hci_interface: 0
  batt_entities: False
  sensor_names:
    '48:57:43:00:a1:5c': 'sypialnia_formaldehyde'
  report_unknown: False
  whitelist: False