- platform: "mqtt"
  name: "kuchnia_smoke_battery"
  state_topic: "zigbee2mqtt/0x00158d0002b0b23f"
  availability_topic: "zigbee2mqtt/0x00158d0002b0b23f/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "kuchnia_smoke_density"
  state_topic: "zigbee2mqtt/0x00158d0002b0b23f"
  availability_topic: "zigbee2mqtt/0x00158d0002b0b23f/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "-"
  value_template: "{{ value_json.smoke_density }}"
  icon: "mdi:google-circles-communities"

#- platform: "mqtt"
#  name: "kuchnia_smoke_sensitivity"
#  state_topic: "zigbee2mqtt/0x00158d0002b0b23f"
#  availability_topic: "zigbee2mqtt/0x00158d0002b0b23f/availability"
#  payload_available: "online"
#  payload_not_available: "offline"
#  value_template: "{{ value_json.sensitivity }}"
