- platform: template
  sensors:
    climate_pokoj_janka_battery:
      value_template: "{% if state_attr('climate.pokoj_janka', 'low_battery') == True -%}5{%- else -%}100{%- endif %}"
      friendly_name: 'Pokój Janka grzejnik'
      unit_of_measurement: '%'
    climate_sypialnia_battery:
      value_template: "{% if state_attr('climate.sypialnia', 'low_battery') == True -%}5{%- else -%}100{%- endif %}"
      friendly_name: 'Sypialnia grzejnik'
      unit_of_measurement: '%'
    climate_salon_battery:
      value_template: "{% if state_attr('climate.salon', 'low_battery') == True -%}5{%- else -%}100{%- endif %}"
      friendly_name: 'salon grzejnik'
      unit_of_measurement: '%'
    zmietekv2_battery:
      value_template: "{{ state_attr('vacuum.zmietekv2', 'battery_level') }}"
      friendly_name: 'Zmietek'
      unit_of_measurement: '%'
    formaldehyde_sypialnia_battery:
      value_template: "{{ state_attr('sensor.mi_formaldehyde_sypialnia_formaldehyde', 'battery_level') }}"
      friendly_name: 'Formaldehyde sypialnia'
      unit_of_measurement: '%'