#- alias: 'Bedside on'
#  initial_state: 'on'
#  trigger:
#    platform: time
#    at: '18:05:00'
#  condition:
#    - condition: state
#      entity_id: light.bedside
#      state: 'off'
#    - condition: state
#      entity_id: binary_sensor.bedside_online
#      state: 'on'
#    - condition: state
#      entity_id: binary_sensor.home_occupied
#      state: 'on'
#  action:
#    - service: light.turn_on
#      data:
#        entity_id: light.bedside
#
#- alias: 'Bedside off'
#  initial_state: 'on'
#  trigger:
#    platform: time
#    at: '09:00:00'
#  action:
#    - service: light.turn_off
#      data:
#        entity_id: light.bedside

- alias: 'Child light on'
  initial_state: 'on'
  trigger:
    platform: time
    at: '18:05:00'
  condition:
    - condition: state
      entity_id: binary_sensor.bedside_online
      state: 'on'
    - condition: state
      entity_id: binary_sensor.home_occupied
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bedside
          - light.lampa_biurko

- alias: 'Child light off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '08:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.bedside
          - light.lampa_biurko