- alias: 'Child light on'
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.home_occupied
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bedside
#          - light.lampa_biurko

- alias: 'Child light off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:31:00'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.bedside
#          - light.lampa_biurko