- alias: 'Włącz światło w sypialni'
  initial_state: 'off'
  description: 'Włącz światło w sypialni na określony czas gdy ruch'
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.sypialnia_motion_occupancy
      to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: '-02:00:00'
    - condition: state
      entity_id: input_boolean.sypialnia_chillout
      state: 'off'
    - condition: state
      entity_id: input_boolean.sypialnia_korki
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.swiatlo_sypialnia
    - delay:
        minutes: 10
    - service: light.turn_off
      data:
        entity_id: light.swiatlo_sypialnia

- alias: 'Zgaś światło w sypialni gdy chillout mode on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.sypialnia_chillout
      to: 'on'
  condition:
    - condition: state
      entity_id: light.swiatlo_sypialnia
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.swiatlo_sypialnia
    - service: fan.set_speed
      data:
        entity_id: fan.purifier
        speed: 'silent'
    - service: fan.set_speed
      data:
        entity_id: fan.smartmi2
        speed: 'silent'

- alias: 'Korki mode on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.sypialnia_korki
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.swiatlo_sypialnia
    - service: light.turn_on
      entity_id: light.yeelight_sypialnia
      data_template:
        brightness: 254
    - service: yeelight.set_mode
      data:
        entity_id: light.yeelight_sypialnia
        mode: normal
