- alias: 'Listwa sypialnia off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '01:05:00'
  condition:
    - condition: state
      entity_id: binary_sensor.listwa_sypiania_used
      state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_sypialnia_switch

- alias: 'Listwa sypialnia on'
  trigger:
    platform: time
    at: '07:05:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: binary_sensor.home_occupied
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_sypialnia_switch

- alias: 'Turn off media (listwa) if switch is available'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.listwa_sypialnia_switch
      from: 'unavailable'
      to: 'on'
      for:
        minutes: 15
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_sypialnia_switch
