- alias: 'Listwa sypialnia off'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '01:05:00'
    - platform: time
      at: '02:05:00'
    - platform: time
      at: '03:05:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_sypialnia_switch

- alias: 'Listwa sypialnia on'
  trigger:
    platform: time
    at: '08:05:00'
  condition:
    - condition: state
      entity_id: binary_sensor.home_occupied
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_sypialnia_switch

- alias: 'Turn off sypialnia listwa after use'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.listwa_sypialnia_switch
      from: 'unavailable'
      to: 'on'
      for:
        minutes: 15
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_sypialnia_switch
