- alias: 'Ambient on'
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.home_occupied
      state: 'on'
  action:
    - service: script.ambient_on

- alias: 'Ambient off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '02:04:00'
  action:
    - service: script.ambient_off

- alias: 'Wyłącz ambient przyciskiem regału'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.salon_regal
      to: 'off'
  action:
    - service: script.ambient_off

- alias: 'Włącz ambient przyciskiem regału'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.salon_regal
      to: 'on'
  action:
    - service: script.ambient_on
