- alias: 'Przykręć ogrzewanie przy otwartych drzwiach w salonie'
  #  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.drzwi_balkonowe_contact, binary_sensor.okno_kuchnia_contact
    to: 'on'
    for:
      seconds: 15
  condition:
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.salon
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Ogrzewanie przykręcone w salonie'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Ogrzewanie przykręcone w salonie

- alias: 'Przykręć ogrzewanie po powrocie przy nadal otwartych drzwiach w salonie'
  #  initial_state: 'on'
  trigger:
    platform: state
    entity_id: climate.salon
    to: 'heat'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.drzwi_balkonowe_contact
          state: 'on'
        - condition: state
          entity_id: binary_sensor.okno_kuchnia_contact
          state: 'on'
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.salon

- alias: 'Przywróć ogrzewanie przy zamkniętych drzwiach w salonie'
  #  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.drzwi_balkonowe_contact, binary_sensor.okno_kuchnia_contact
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.salon
    - delay: 00:00:10
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.salon
        hvac_mode: auto
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Ogrzewanie przywrócone w salonie'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Ogrzewanie przywrócone w salonie