- alias: 'Włącz listwę i ampli przy włączeniu tv'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.listwa_salon_slot_1
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_salon_slot_1
    - delay: 00:00:05
    - service: input_select.select_option
      data:
        entity_id: input_select.broadlink_denon_input
        option: 'TV'

- alias: 'Wyłącz ampli przy wyłączonym tv i chromecast'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.rtv_used
      to: 'off'
      for:
        seconds: 45
  condition:
    - condition: state
      entity_id: switch.listwa_salon_slot_1
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_salon_slot_1

- alias: 'Ustaw zrodło ampli na chromecast gdy gra'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.salon
      to: 'playing'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.broadlink_denon_input
        option: 'Chromecast'

- alias: 'Ustaw zrodło ampli na tv gdy chromecast juz nie gra'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.salon
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.broadlink_denon_input
        option: 'TV'

- alias: 'Turn off media (xbox) if switch is available'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.xbox_power_switch
      from: 'unavailable'
      to: 'on'
      for:
        minutes: 15
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.xbox_power_switch
