homeassistant:
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
  external_url: !secret base_url
  internal_url: http://synology.lan:8123

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
map:
sun:
mobile_app:
person:
system_health:
logbook:
python_script:
ffmpeg:

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

history: !include history.yaml
recorder: !include recorder.yaml
zone: !include_dir_merge_list zones

camera: !include cameras/dafang.yaml
timer: !include timer/timer.yaml
group: !include_dir_named groups
automation: !include_dir_merge_list automation
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
switch: !include_dir_merge_list switches
cover: !include cover/shellys.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include_dir_merge_named input_selects
weather: !include weather/darksky.yaml
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_player
yeelight: !include yeelight/yeelight.yaml
plant: !include plants/plants.yaml

speedtestdotnet:
  server_id: 7202
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping


vacuum:
  - platform: xiaomi_miio
    host: roborock.lan
    name: zmietekv2
    token: !secret vacuum

fan:
  - platform: xiaomi_miio
    host: airpurifier.lan
    name: purifier
    token: !secret purifier

  - platform: xiaomi_miio
    host: smartmi.lan
    name: smartmi2
    token: !secret smartmi2

notify:
  - name: mypushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

#climate:
#  - platform: eq3btsmart
#    devices:
#      pokoj-janka:
#        mac: '00:1A:22:0C:1A:F2'
#      sypialnia:
#        mac: '00:1A:22:0C:1A:EF'
#      salon:
#        mac: '00:1A:22:11:5D:B3'
#
asuswrt:
  host: router.lan
  username: !secret device_tracker_asus_username
  ssh_key: /config/ssh/ssh_asus_private_key
  interface: 'eth0'
  dnsmasq: '/var/lib/misc'
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

device_tracker:
  - platform: asuswrt
    host: router.lan
    username: !secret device_tracker_asus_username
    password: !secret device_tracker_asus_password
    interval_seconds: 60
    new_device_defaults:
      track_new_devices: false
