homeassistant:
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
  external_url: !secret base_url
  internal_url: http://synology.lan:8123

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
map:
sun:
mobile_app:
person:
system_health:
logbook:
python_script:
ffmpeg:
wake_on_lan:
system_log:
  max_entries: 200
logger:
  default: info
  logs:
    # log level for HA core
#    homeassistant.core: fatal
    # log level for MQTT integration
    homeassistant.components: warning
    homeassistant.components.python_script: warning
#    aiohttp: debug
#    homeassistant.components.asuswrt: debug
    homeassistant.components.vacuum: critical
    libav.tcp: critical
    homeassistant.components.automation: warning
    homeassistant.loader: warning
    homeassistant.config_entries: critical
    homeassistant.helpers.entity: critical
    homeassistant.components.stream.worker: critical
    homeassistant.components.wled: critical
    homeassistant.components.yeelight: critical
    homeassistant.components.eq3btsmart.climate: critical
    homeassistant.components.climate: critical
    homeassistant.components.recorder: critical

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

history: !include history.yaml
recorder: !include recorder.yaml
zone: !include_dir_merge_list zones

camera: !include_dir_merge_list cameras
timer: !include timer/timer.yaml
group: !include_dir_named groups
automation: !include_dir_merge_list automation
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
switch: !include_dir_merge_list switches
cover: !include cover/shellys.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include_dir_merge_named input_selects
weather: !include weather/darksky.yaml
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_player
yeelight: !include yeelight/yeelight.yaml
plant: !include plants/plants.yaml

vacuum:
  - platform: xiaomi_miio
    host: roborock.lan
    name: zmietekv2
    token: !secret vacuum

fan:
  - platform: xiaomi_miio
    host: airpurifier.lan
    name: purifier
    token: !secret purifier

  - platform: xiaomi_miio
    host: smartmi.lan
    name: smartmi2
    token: !secret smartmi2

notify:
  - name: mypushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

climate:
  - platform: eq3btsmart
    devices:
      pokoj-janka:
        mac: '00:1a:22:0c:1a:f2'
      sypialnia:
        mac: '00:1a:22:0c:1a:ef'
      salon:
        mac: '00:1a:22:11:5d:b3'

asuswrt:
  host: 192.168.1.1
  port: 2225
  username: !secret device_tracker_asus_username
#  password: !secret device_tracker_asus_password
  ssh_key: /config/ssh/ssh_asus_private_key
  interface: 'eth0'
  dnsmasq: '/var/lib/misc'
  sensors:
    - devices
#    - upload
#    - download
#    - upload_speed
#    - download_speed

ble_monitor:
  rounding: True
  decimals: 1
  period: 120
  log_spikes: False
  use_median: False
  active_scan: False
  hci_interface: 1
  batt_entities: False
  discovery: False
  report_unknown: False
  devices:
    - mac: '48:57:43:00:a1:5c'
      name: 'sypialnia formaldehyde'
    - mac: 'C4:7C:8D:6B:1A:B3'
      name: 'monstera'
    - mac: 'C4:7C:8D:6B:24:C7'
      name: 'diffenbachia'
    - mac: 'C4:7C:8D:6B:5A:B1'
      name: 'ficus lyrata'
    - mac: 'C4:7C:8D:6B:5A:B1'
      name: 'ficus lyrata'
    - mac: 'C4:7C:8D:6A:01:92'
      name: 'cycas circinalis'
#    - mac: 'A4:C1:38:A3:70:35'
#      name: 'pokoj dzieci'
#      encryption_key: '???'
