db_url: !secret db_url
exclude:
  domains:
    - weather
    - updater
    - group
    - zone
    - media_player
  entities:
    - sun.sun # Don't record sun data
    - sensor.last_boot # Comes from 'systemmonitor' sensor platform
    - sensor.date
    - sensor.swiatlo_pokoj_janka_version
    - sensor.swiatlo_sypialnia_version
    - sensor.lampa_salon_version
    - sensor.salon_regal_version
    - sensor.listwa_rtv_version
    - sensor.listwa_sypialnia_version
    - sensor.zmietek_version
    - sensor.rtv_jan_version
    - sensor.climate_pokoj_janka_battery
    - sensor.climate_sypialnia_battery
    - sensor.climate_salon_battery
    - sensor.zmietekv2_battery
    - sensor.kuchnia_temp_battery
    - sensor.korytarz_temp_battery
    - sensor.drzwi_balkonowe_contact_battery
    - sensor.sypialnia_motion_battery
    - sensor.okno_sypialnia_contact_battery
    - sensor.lazienka_motion_battery
    - sensor.korytarz_motion_battery
    - sensor.okno_janek_contact_battery
    - sensor.janek_motion_battery
    - sensor.drzwi_wejsciowe_contact_battery
    - sensor.drzwi_lazienka_contact_battery
    - sensor.drzwi_toaleta_contact_battery
    - sensor.okno_kuchnia_contact_battery
    - sensor.kuchnia_leak_battery
    - sensor.lazienka_leak_battery
    - sensor.custom_component_tracker
    - sensor.custom_python_script_tracker
    - sensor.humidifier_motor_speed
    - sensor.motor_speed
    - sensor.purifier_filter_type
    - sensor.purifier_filter_life_remaining
    - sensor.vacuum_fan
    - sensor.vacuum_cleaned_area
    - sensor.vacuum_battery
    - sensor.vacuum_cleaning_time
    - sensor.vacuum_main_brush
    - sensor.vacuum_side_brush
    - sensor.vacuum_filter
    - sensor.vacuum_cleaning_count
    - sensor.dark_sky_temperature
    - sensor.dark_sky_uv_index
    - sensor.dark_sky_uv_index_0d
    - sensor.dark_sky_uv_index_1d
    - sensor.dark_sky_uv_index_2d
    - sensor.dark_sky_uv_index_3d
    - sensor.dark_sky_uv_index_4d
    - sensor.dark_sky_uv_index_5d
    - sensor.dark_sky_nearest_storm_bearing
    - sensor.dark_sky_nearest_storm_distance
    - sensor.dark_sky_overnight_low_apparent_temperature_0d
    - sensor.dark_sky_overnight_low_apparent_temperature_1d
    - sensor.dark_sky_overnight_low_apparent_temperature_2d
    - sensor.dark_sky_overnight_low_apparent_temperature_3d
    - sensor.dark_sky_overnight_low_apparent_temperature_4d
    - sensor.dark_sky_overnight_low_apparent_temperature_5d
    - sensor.dark_sky_daytime_high_temperature_1d
    - sensor.dark_sky_daytime_high_temperature_2d
    - sensor.dark_sky_daytime_high_temperature_3d
    - sensor.dark_sky_daytime_high_temperature_4d
    - sensor.dark_sky_daytime_high_temperature_5d
    - sensor.dark_sky_icon
    - sensor.dark_sky_icon_1d
    - sensor.dark_sky_icon_2d
    - sensor.dark_sky_icon_3d
    - sensor.dark_sky_icon_4d
    - sensor.dark_sky_icon_5d
    - sensor.dark_sky_overnight_low_temperature_0d
    - sensor.dark_sky_overnight_low_temperature_1d
    - sensor.dark_sky_overnight_low_temperature_2d
    - sensor.dark_sky_overnight_low_temperature_3d
    - sensor.dark_sky_overnight_low_temperature_4d
    - sensor.dark_sky_summary
    - sensor.dark_sky_summary_0d
    - sensor.dark_sky_summary_1d
    - sensor.dark_sky_summary_2d
    - sensor.dark_sky_summary_3d
    - sensor.dark_sky_summary_4d
    - sensor.dark_sky_summary_5d
    - sensor.dark_sky_visibility
    - sensor.dark_sky_visibility_0d
    - sensor.dark_sky_visibility_1d
    - sensor.dark_sky_visibility_2d
    - sensor.dark_sky_visibility_3d
    - sensor.dark_sky_visibility_4d
    - sensor.dark_sky_visibility_5d
    - sensor.dark_sky_daytime_high_temperature_0d
    - sensor.dark_sky_daytime_high_temperature_1d
    - sensor.dark_sky_daytime_high_temperature_2d
    - sensor.dark_sky_daytime_high_temperature_3d
    - sensor.dark_sky_daytime_high_temperature_4d
    - sensor.dark_sky_daytime_high_temperature_5d
    - sensor.dark_sky_daytime_high_apparent_temperature_0d
    - sensor.dark_sky_daytime_high_apparent_temperature_1d
    - sensor.dark_sky_daytime_high_apparent_temperature_2d
    - sensor.dark_sky_daytime_high_apparent_temperature_3d
    - sensor.dark_sky_daytime_high_apparent_temperature_4d
    - sensor.dark_sky_daytime_high_apparent_temperature_5d
    - sensor.dark_sky_wind_bearing
    - sensor.dark_sky_wind_bearing_0d
    - sensor.dark_sky_wind_bearing_1d
    - sensor.dark_sky_wind_bearing_2d
    - sensor.dark_sky_wind_bearing_3d
    - sensor.dark_sky_wind_bearing_4d
    - sensor.dark_sky_wind_bearing_5d
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_wind_speed_0d
    - sensor.dark_sky_wind_speed_1d
    - sensor.dark_sky_wind_speed_2d
    - sensor.dark_sky_wind_speed_3d
    - sensor.dark_sky_wind_speed_4d
    - sensor.dark_sky_wind_speed_5d
    - sensor.dark_sky_humidity
    - sensor.dark_sky_humidity_0d
    - sensor.dark_sky_humidity_1d
    - sensor.dark_sky_humidity_2d
    - sensor.dark_sky_humidity_3d
    - sensor.dark_sky_humidity_4d
    - sensor.dark_sky_humidity_5d
    - sensor.dark_sky_pressure
    - sensor.dark_sky_pressure_0d
    - sensor.dark_sky_pressure_1d
    - sensor.dark_sky_pressure_2d
    - sensor.dark_sky_pressure_3d
    - sensor.dark_sky_pressure_4d
    - sensor.dark_sky_pressure_5d
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_precip_intensity_0d
    - sensor.dark_sky_precip_intensity_1d
    - sensor.dark_sky_precip_intensity_2d
    - sensor.dark_sky_precip_intensity_3d
    - sensor.dark_sky_precip_intensity_4d
    - sensor.dark_sky_precip_intensity_5d
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_precip_probability_0d
    - sensor.dark_sky_precip_probability_1d
    - sensor.dark_sky_precip_probability_2d
    - sensor.dark_sky_precip_probability_3d
    - sensor.dark_sky_precip_probability_4d
    - sensor.dark_sky_precip_probability_5d
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_0d
    - sensor.dark_sky_precip_1d
    - sensor.dark_sky_precip_2d
    - sensor.dark_sky_precip_3d
    - sensor.dark_sky_precip_4d
    - sensor.dark_sky_precip_5d
    - sensor.dark_sky_precip_accumulation_0d
    - sensor.dark_sky_precip_accumulation_1d
    - sensor.dark_sky_precip_accumulation_2d
    - sensor.dark_sky_precip_accumulation_3d
    - sensor.dark_sky_precip_accumulation_4d
    - sensor.dark_sky_precip_accumulation_5d