- platform: template
  sensors:
    home_occupied:
      friendly_name: Home Occupied
      entity_id:
        - group.mobiledevices
        - input_boolean.guest_mode
      device_class: occupancy
      value_template: >-
        {{- is_state('group.mobiledevices', 'home')
          or
        is_state('input_boolean.guest_mode' , 'on') -}}
    rtv_used:
      friendly_name: RTV used
      entity_id:
        - media_player.salon
        - media_player.sony_bravia_tv
      value_template: >-
        {{- is_state('media_player.salon','playing')
          or
        is_state('media_player.salon','paused')
          or
        is_state('media_player.sony_bravia_tv','on') -}}
    listwa_sypiania_used:
      friendly_name: Listwa sypialnia used
      entity_id:
        - media_player.sypialnia_chromecast
      value_template: >-
        {{- is_state('media_player.sypialnia_chromecast','playing')
          or
        is_state('media_player.sypialnia_chromecast','paused') -}}
