- platform: template
  sensors:
    home_occupied:
      friendly_name: Home Occupied
      device_class: occupancy
      value_template: >-
        {{- is_state('group.mobiledevices', 'home')
          or
        is_state('input_boolean.guest_mode' , 'on') -}}
    rtv_used:
      friendly_name: RTV used
      value_template: >-
        {{- is_state('media_player.salon','playing')
          or
        is_state('media_player.salon','paused')
          or
        is_state('media_player.sony_bravia_tv','on') -}}

